# first stage
FROM debian:stable AS downloader
RUN apt update && apt install -y \
  curl \
  unzip
WORKDIR /download
ARG PAK_URL=https://downloads.sourceforge.net/project/simutrans/pak64/123-0/simupak64-123-0.zip
RUN curl -L -o pak.zip ${PAK_URL} && \
  unzip pak.zip && rm pak.zip

# second stage
FROM yoryan/simutrans-server:steam
ARG PAK_DIR=pak
COPY --from=downloader /download/simutrans/${PAK_DIR}/ /game/pak/
ENTRYPOINT ["/game/simutrans", "-server", "-singleuser", "-objects", "pak"]