name: Push to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push steam/standard core
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.core
          tags: yoryan/simutrans-server:steam-standard
      -
        name: Build and push steam/standard pak128
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.with-pak
          secrets: |
            "steam_login=${{ secrets.STEAM_LOGIN }}"
          build-args: |
            DLC_DEPOT=434529
            PAK_DIR=pak128
          tags: yoryan/simutrans-server:steam-standard-pak128
      -
        name: Build and push steam/standard pak64
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.with-pak
          secrets: |
            "steam_login=${{ secrets.STEAM_LOGIN }}"
          build-args: |
            DLC_DEPOT=434630
            PAK_DIR=pak64
          tags: yoryan/simutrans-server:steam-standard-pak64
      -
        name: Build and push steam/standard pak128.britain
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.with-pak
          secrets: |
            "steam_login=${{ secrets.STEAM_LOGIN }}"
          build-args: |
            DLC_DEPOT=434631
            PAK_DIR=pak128.Britain
          tags: yoryan/simutrans-server:steam-standard-pak128.britain
      -
        name: Build and push steam/standard pak192.comic
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.with-pak
          secrets: |
            "steam_login=${{ secrets.STEAM_LOGIN }}"
          build-args: |
            DLC_DEPOT=434632
            PAK_DIR=pak192.comic
          tags: yoryan/simutrans-server:steam-standard-pak192.comic
      -
        name: Build and push steam/standard pak128.german
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.with-pak
          secrets: |
            "steam_login=${{ secrets.STEAM_LOGIN }}"
          build-args: |
            DLC_DEPOT=434633
            PAK_DIR=pak128.german
          tags: yoryan/simutrans-server:steam-standard-pak128.german
      -
        name: Build and push steam/standard pak128.japan
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.with-pak
          secrets: |
            "steam_login=${{ secrets.STEAM_LOGIN }}"
          build-args: |
            DLC_DEPOT=435960
            PAK_DIR=pak128.japan
          tags: yoryan/simutrans-server:steam-standard-pak128.japan
      -
        name: Build and push steam/standard pak64.german
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:steam-standard"
          platforms: linux/amd64
          file: Dockerfile.with-pak
          secrets: |
            "steam_login=${{ secrets.STEAM_LOGIN }}"
          build-args: |
            DLC_DEPOT=435963
            PAK_DIR=pak64.german
          tags: yoryan/simutrans-server:steam-standard-pak64.german
