name: Push to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push core
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          file: Dockerfile
          tags: yoryan/simutrans-server:steam
      -
        name: Build and push pak64
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          file: Dockerfile.pak
          build-args: |
            PAK_URL=https://downloads.sourceforge.net/project/simutrans/pak64/123-0/simupak64-123-0.zip
            PAK_DIR=pak
          tags: yoryan/simutrans-server:steam-pak64
